Repository JayShukla8/Quotes, pull requests merged in 2024-10, with the labels that each got.

#22 feat(quotes): add quotes of Prophet Muhammad(s)
  data.json
Labels: hacktoberfest-accepted, hacktoberfest

#25 added light/dark mode toggle
  index.html
  mode.js
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#36 Added 2 new quotes
  data.json
Labels: hacktoberfest-accepted, hacktoberfest

#57 Adding ISSUE and PR template [ISSUE-#18]
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PR_Template.md
Labels: hacktoberfest-accepted, hacktoberfest

#58 Adding LICENSE and Code Of Conduct - [ISSUE -#19]
  Code Of Conduct.md
  LICENSE
Labels: hacktoberfest-accepted, hacktoberfest

#33 Copy and Share Icon with every Quote #26
  index.html
  script.js
  style.css
Labels: hacktoberfest-accepted

#38 added the class heading-text and in dark mode css change its colour
  style.css
Labels: hacktoberfest-accepted

#42 Add some Quotes from different persons
  data.json
Labels: hacktoberfest-accepted

#52 Update data.json
  data.json
Labels: hacktoberfest-accepted, Hacktoberfest 2024

#50 Update data.json
  data.json
Labels: hacktoberfest-accepted

#53 Adding new quote as beginner in Hacktober fest 2024
  data.json
Labels: hacktoberfest-accepted

#54 Updated Quotes
  data.json
Labels: hacktoberfest-accepted

#55 Adding some good and popular quotes by Martin Luther King Jr. and Rabindranath Tagore
  data.json
Labels: hacktoberfest-accepted

#56 Added new quote
  .all-contributorsrc
  data.json
Labels: hacktoberfest-accepted

#60 Added some styling and quotes! (Good First issue)
  data.json
  style.css
Labels: hacktoberfest-accepted

#63 New quote added
  data.json
Labels: Hacktoberfest 2024

#74 added new quote
  data.json
Labels: hacktoberfest-accepted

#90 Added quote
  data.json
Labels: hacktoberfest-accepted

#95 FEATURE: Add voice narration
  index.html
  script.js
Labels: hacktoberfest-accepted

#39 made changes in the background for light and dark mode and added back…
  images/bubbles.png
  images/stains.png
  images/stars.png
  style.css
Labels: hacktoberfest-accepted

#102 Updated and reduced the quotes to one
  data.json
Labels: hacktoberfest-accepted

#79 MORE DIVERSED QUOTES
  data.json
Labels: hacktoberfest-accepted

#89 Made changes in the hover effect of the quote card
  script.js
  style.css
Labels: hacktoberfest

#92 Feature/back to top
  index.html
  script.js
  style.css
Labels: hacktoberfest-accepted

#93 added quote
  data.json
Labels: hacktoberfest-accepted

#100 added 2 new quotes
  data.json
Labels: hacktoberfest-accepted

#103 Update data.json
  data.json
Labels: hacktoberfest-accepted

#107 Add 1 New Quotes
  data.json
  script.js
  style.css
Labels: hacktoberfest

#115 add: Update data.json
  data.json
Labels: hacktoberfest-accepted

#117 adding scroll driven animations for quotes
  style.css
Labels: hacktoberfest-accepted

#120 Adding a quote by Albert Einstein
  data.json
Labels: hacktoberfest-accepted

#124 Add like functionality
  script.js
  style.css
Labels: hacktoberfest-accepted

#125 footer added #16
  index.html
  style.css
Labels: hacktoberfest-accepted

#126 Added new quote
  data.json
Labels: hacktoberfest-accepted

#127 Add new qoutes
  data.json
Labels: hacktoberfest-accepted

#129 feat: add mandela quote
  data.json
Labels: hacktoberfest

#130 Added one quote to data.json
  data.json
Labels: hacktoberfest-accepted

#133 Update data.json
  data.json
Labels: hacktoberfest-accepted

#123 Added Quote
  data.json
Labels: hacktoberfest-accepted

#136 Updated data.json
  data.json
Labels: hacktoberfest-accepted

#137 Added Quote
  data.json
Labels: hacktoberfest-accepted

#134 Chibuike 19/fix overlaping content
  script.js
  style.css
Labels: hacktoberfest-accepted

#139 Added quotes
  data.json
Labels: hacktoberfest-accepted

#141 Added quote from atomic habit: My favourite.
  data.json
Labels: hacktoberfest-accepted

#142 feat: added einstein quote
  data.json
Labels: hacktoberfest-accepted

#143 added a quote in data.json
  data.json
Labels: hacktoberfest-accepted

#144 Update data.json
  data.json
Labels: hacktoberfest-accepted

#145 Added quote
  data.json
Labels: hacktoberfest-accepted

#148 Added Quote without touching anything else
  data.json
Labels: hacktoberfest-accepted

#140 feature/quote-to-image-maker
  index.html
  quoteImage.js
  script.js
Labels: hacktoberfest-accepted

#150 Added a new quote, didn't change anything else
  data.json
Labels: hacktoberfest-accepted

#151 add-quote
  data.json
Labels: hacktoberfest-accepted

#152 Update data.json
  data.json
Labels: hacktoberfest-accepted

#154 Added search feature
  data.json
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest-accepted

#158 Update data.json
  data.json
Labels: hacktoberfest-accepted

#159 Alphabetical ordering tags for easier navigation.
  script.js
Labels: hacktoberfest-accepted

#160 Added a new quote in data.json
  data.json
Labels: hacktoberfest-accepted

#163 Added Nietzsche quote
  data.json
Labels: hacktoberfest-accepted

#170 Update data.json
  data.json
Labels: hacktoberfest-accepted

#171 Added Osho quote.
  data.json
Labels: hacktoberfest

#179 Mahatma Gandhi quote added
  data.json
Labels: hacktoberfest-accepted

#180 Added the Abraham Lincoin Quote on self-determination
  data.json
Labels: hacktoberfest-accepted

#182 Fetching json tags done.
  script.js
Labels: hacktoberfest-accepted

#183 Add a quote by Ivan Nuru and unify the formatting of `data.json`.
  data.json
Labels: hacktoberfest-accepted

#187 Added a quote
  data.json
Labels: hacktoberfest-accepted

#178 Added david viscott quote.
  data.json
Labels: hacktoberfest-accepted

#188 Added Steve Jobs Quote from 2005 Address.
  data.json
Labels: hacktoberfest-accepted

#191 Bhagat Singh quote added
  data.json
Labels: hacktoberfest-accepted

#189 Make nav-bar mobile responsive
  index.html
  style.css
Labels: hacktoberfest-accepted

#193 Added 2 unique quotes
  data.json
Labels: hacktoberfest-accepted

#197 updated "quote" color.
  style.css
Labels: hacktoberfest-accepted

#198 Added data to data.json
  data.json
Labels: hacktoberfest-accepted

#201 Added quote.
  data.json
Labels: hacktoberfest-accepted

#200 Update data.json
  data.json
Labels: hacktoberfest-accepted

#203 feat: add new quote from Ave Mateiu
  data.json
Labels: hacktoberfest-accepted

#206 Kenyan
  data.json
Labels: hacktoberfest-accepted

#207 Update data.json
  data.json
Labels: hacktoberfest-accepted

#211 I've added two new quotes
  data.json
Labels: hacktoberfest-accepted

#213 added 2 quotes
  data.json
Labels: hacktoberfest-accepted

#212 Added Bhagavad Gita quotes
  data.json
Labels: hacktoberfest-accepted, hacktoberfest, gssoc-ext, level2

#218 Update data.json
  data.json
Labels: hacktoberfest-accepted

#214 Navbar Dropdown Updation.
  index.html
  style.css
Labels: hacktoberfest-accepted

#224 Added quotes
  data.json
Labels: hacktoberfest-accepted

#225 Added new quotes
  data.json
Labels: hacktoberfest-accepted

#227 Adding new quote
  data.json
Labels: hacktoberfest-accepted

#228 Added a quote by Swami vivekananda in data.json
  data.json
Labels: hacktoberfest-accepted

#229 Update data.json
  data.json
Labels: hacktoberfest-accepted, Hacktoberfest 2024

#230 Update data.json
  data.json
Labels: hacktoberfest-accepted, Hacktoberfest 2024

#231 Updated data.json
  data.json
Labels: hacktoberfest-accepted

#232 add new quote
  data.json
Labels: hacktoberfest-accepted

#233 Updated data.json
  data.json
Labels: hacktoberfest-accepted
